### PR TITLE
Fix wrong marshalling for static member arrays

### LINKED ISSUE #1417: static T array[] generates (uncompilable | incorrect) and slow code
##### Brief Description

Using `char [] array` generates uncompilable code but using a type which uses more storage like short generates compilable but incorrect code.

OS: Windows

##### Used settings

Target: MSVC

##### Stack trace or incompilable generated code

```.cs
// DEBUG: static char static_array[100]
public static sbyte[] StaticArray
{
    get
    {
        var __ptr = (byte*)CppSharp.SymbolResolver.ResolveSymbol("TestLib", "?static_array@Class@@2PADA");
        sbyte[] __value = null;
        if (__ptr != null)
        {
            __value = new sbyte[100];
            for (int i = 0; i < 100; i++)
                __value[i] = __ptr[i]; // CS0266: Cannot implicitly convert type 'byte' to 'sbyte'. An explicit conversion 
        }
        return __value;
    }
}
```

### PR DESCRIPTION
**Pull request by josetr**
Fixes #1417

### CODE REVIEW

**Comment by tritao** [comment]
The build is failing on the bot:

```
C:\projects\cppsharp\build\vs2019\gen\Common\Common_GenerateName.cs(1413,21): error CS0019: Operator '==' cannot be applied to operands of type 'sbyte*' and 'IntPtr' [C:\projects\cppsharp\tests\Common\Common.CSharp.csproj]
```

I'm assuming its something caused by these changes, can you take a look?

**Comment by josetr** [comment]
Now it's failing also due to #1419 as well.

**Comment by ddobrev** [comment]
Thank you, @josetr .
`C:\projects\cppsharp\build\vs2019\gen\Common\Common_GenerateName.cs(1413,21): error CS0019: Operator '==' cannot be applied to operands of type 'sbyte*' and 'IntPtr' [C:\projects\cppsharp\tests\Common\Common.CSharp.csproj]` is no longer a problem but now `C:\projects\cppsharp\build\vs2019\gen\CSharp\CSharp.cs(33471,68): error CS0021: Cannot apply indexing with [] to an expression of type 'IntPtr' [C:\projects\cppsharp\tests\CSharp\CSharp.CSharp.csproj]`'s appeared.

**Comment by ddobrev** [comment]
@josetr much better, Windows passed now. Unfortunately, Unix doesn't. The reason is that default initialization of members is often inlined, and we don't automatically support inlined code yet (I've been working on it but it's difficult and not done yet). Therefore for this test to work all initialization must move to C++ as you've already done with 2 of your constants.

**Comment by josetr** [comment]
Yes they issue is related to https://github.com/mono/CppSharp/issues/1421 which I've reported as well. What I've done in my local repo is expose an `internal` `Initializer` in the `Variable` class and store the expression from `clang::VarDecl::getAnyInitializer()`. It's storing an `ExpressionObsolete` and I'm using bits like `CheckForSimpleExpressions` from the `HandleDefaultParamValuesPass` class therefore it has similar issues like not supporting every possible valid C++ expression but the most common usage for static const variables is storing integral types and that is supported.

**Comment by ddobrev** [comment]
You're correct that having the feature of "constants as constants" would solve this issue too. But while we don't have it yet, tests should keep working with whatever approach we use at present. Therefore there's little option but to move the initializations to `cpp`.
The pieces of code you mention are definitely going to be useful when we go about this feature. So let's merge this PR after the tests pass and we can discuss proceeding.

**Comment by josetr** [comment]
I agree and I was about to do that. I just wanted to share what I've done in case that is good to turn into a pull request.

**Comment by ddobrev** [comment]
It does sound good. Even if there's anything to improve, we'll catch it in the review.

**Comment by tritao** [comment]
> Yes they issue is related to #1421 which I've reported as well. What I've done in my local repo is expose an `internal` `Initializer` in the `Variable` class and store the expression from `clang::VarDecl::getAnyInitializer()`. It's storing an `ExpressionObsolete` and I'm using bits like `CheckForSimpleExpressions` from the `HandleDefaultParamValuesPass` class therefore it has similar issues like not supporting every possible valid C++ expression but the most common usage for static const variables is storing integral types and that is supported.

That sounds reasonable, feel free to send a PR.
